// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaC-6ec5WCKTFeqQn0bOL1wILtY1hm-ZY',
    appId: '1:905464757558:web:a969081156ccf8876a8797',
    messagingSenderId: '905464757558',
    projectId: 'smart-placement-assistan-a54bd',
    authDomain: 'smart-placement-assistan-a54bd.firebaseapp.com',
    storageBucket: 'smart-placement-assistan-a54bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlu781cFzeTaEdd7iT1MaUs4KLA0_OoQg',
    appId: '1:905464757558:android:65d600d58da8902c6a8797',
    messagingSenderId: '905464757558',
    projectId: 'smart-placement-assistan-a54bd',
    storageBucket: 'smart-placement-assistan-a54bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKKmTHTTDgjG0yI3wT98LJTHMvT2GRluo',
    appId: '1:905464757558:ios:91b992121d6689e86a8797',
    messagingSenderId: '905464757558',
    projectId: 'smart-placement-assistan-a54bd',
    storageBucket: 'smart-placement-assistan-a54bd.firebasestorage.app',
    androidClientId: '905464757558-v4n7ghgr3c0mbfmp0ulfqbpbbv0omgv6.apps.googleusercontent.com',
    iosClientId: '905464757558-uaa0rcc9co67hptdm9tle7db6t34cgnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartPlacementAssistantNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaC-6ec5WCKTFeqQn0bOL1wILtY1hm-ZY',
    appId: '1:905464757558:web:b8831c7fcfecb49d6a8797',
    messagingSenderId: '905464757558',
    projectId: 'smart-placement-assistan-a54bd',
    authDomain: 'smart-placement-assistan-a54bd.firebaseapp.com',
    storageBucket: 'smart-placement-assistan-a54bd.firebasestorage.app',
  );
}
